- hosts: prod_integ
  tasks:
  - name: copy python scripts
    copy:
      src: {{ item.src }} dest: {{ item.dest }}
      with_items:
        - { src: '../scripts/historique_to_elastic.py', dest: 'project/historique_to_elastic.py' }
        - { src: '../scripts/price_index_to_kafka_realtime.py', dest: 'project/price_index_to_kafka_realtime.py' }
        - { src: '../scripts/spark_stream_from_kafka_realtime.py', dest: 'project/spark_stream_from_kafka_realtime.py' }
  - name: ensure that pip is already installed
    apt: name=python-pip state=latest
    become: yes
  - name: install python packages elasticsearch requests pyspark
    pip: name={{ item }}
    with_items:
      - elasticsearch
      - kafka
      - requests
      - pyspark
  - name: run python scripts
    command: python "{{ item.filename }}" {{ item.args }}
    with_items:
      - { filename: "project/historique_to_elastic.py", args: "51.15.140.26 9200" }
      - { filename: "project/price_index_to_kafka_realtime.py" args: ""}
      - { filename: "project/spark_stream_from_kafka_realtime.py", args: "localhost:9092 bitcoin-realtime 51.15.140.26 9200 EUR" }

